on:
  - "push"
  - "pull_request"

jobs:
  build:

    runs-on: "ubuntu-18.04"
    strategy:
      max-parallel: 4
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']

    steps:
    - uses: "actions/checkout@v2.0.0"
    - name: "Cache dependencies installed with composer"
      uses: "actions/cache@v1.0.3"
      with:
        path: "~/.composer/cache"
        key: "composer-${{ matrix.php-version }}-${{ hashFiles('composer.json') }}"
        restore-keys: "composer-${{ matrix.php-version }}-"
    - name: "Setup PHP Action"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-versions }}"
        extensions: "intl, xdebug"

    - name: "Composer install"
      run: "composer update --no-interaction --no-progress --no-suggest"
    - name: "PHPStan"
      run: "vendor/bin/phpstan analyse"
    - name: "Run tests"
      run: "vendor/bin/phpunit"
    - name: "Mutation tests"
      run: "vendor/bin/infection --min-msi=95"
